theme: jekyll-theme-minimal
# remote_theme           : "mmistakes/minimal-mistakes"
minimal_mistakes_skin    :  "contrast" # "default" "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale                   : "en-US"
title                    : "꿈공장"
title_separator          : "-"
name                     : "DONGHWAN, KIM"
description              : "An amazing website."
url                      : "https://yearnlune.github.io"
baseurl                  : "/"
repository               : "yearnlune/yearnlune.github.io"
teaser                   : # path of fallback teaser image, e.g. "/assets/images/500x300.png"
logo                     : # path of logo image to display in the masthead, e.g. "/assets/images/88x88.png"
masthead_title           : # overrides the website title displayed in the masthead, use " " for no title
